#!/usr/bin/env python3
"""
Power Supply 2 Schematic Generator for fcBoard

Generates a clean KiCad schematic with:
- 12V DC Input (Barrel Jack)
- LM2596S-5.0 (12V → 5V)
- LM2596S-ADJ (12V → 3.3V)
- LM2596S-ADJ (12V → 1.8V)
- LED indicators for each rail
- Proper decoupling capacitors

IMPORTANT: This script uses lib_id references to external libraries.
- KiCad default libraries (Device, Connector, power, Regulator_Switching)
- jlc_components library (generated by easyeda2kicad via gen_jlc_lib.py)

The lib_symbols section is intentionally empty - KiCad will load symbols
from the referenced libraries when opening the schematic.

Usage:
    python scripts/generate_power_supply2.py
"""

import uuid
from pathlib import Path


SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
OUTPUT_FILE = PROJECT_ROOT / "fcBoard_Power2.kicad_sch"

# Library configuration
# Use KiCad default libraries for standard components
# Use jlc_components for JLCPCB/LCSC sourced parts
JLC_LIB = "jlc_components"


def gen_uuid():
    """Generate a random UUID."""
    return str(uuid.uuid4())


def generate_schematic():
    """Generate the complete Power Supply 2 schematic."""

    sch = f'''(kicad_sch
	(version 20231120)
	(generator "python_script")
	(generator_version "1.0")
	(uuid "{gen_uuid()}")
	(paper "A3")
	(title_block
		(title "Power Supply 2")
		(date "2024-12-11")
		(rev "1.0")
		(company "fcBoard Project")
		(comment 1 "12V Input, 5V/3.3V/1.8V DC-DC Outputs")
		(comment 2 "Generated by Python script")
	)
	(lib_symbols
{generate_lib_symbols()}
	)
{generate_instances()}
{generate_wires()}
)
'''
    return sch


def generate_lib_symbols():
    """
    Generate library symbol definitions.

    IMPORTANT: This function returns an EMPTY string intentionally.
    Symbols are NOT embedded in the schematic file.
    KiCad will load symbols from external libraries via lib_id references.

    Referenced libraries:
    - Device: R, C, CP, L, LED, D_Schottky (KiCad default)
    - Connector: Barrel_Jack_Switch (KiCad default)
    - Regulator_Switching: LM2596S-5, LM2596S-ADJ (KiCad default)
    - power: GND, +12V, +5V, +3V3, +1V8 (KiCad default)
    - jlc_components: LCSC parts (generated by easyeda2kicad)

    When you open the schematic in KiCad, it will automatically resolve
    the lib_id references and load the actual symbol graphics from the
    installed libraries.
    """
    # Return empty - KiCad loads symbols from external libraries via lib_id
    return ''


def generate_instances():
    """Generate component instances."""
    instances = []

    # ==================== 12V INPUT SECTION ====================
    # Barrel Jack J1 at (50, 60)
    instances.append(create_symbol("Connector:Barrel_Jack_Switch", "J1", "DC_12V", 50, 60,
                                   "Connector_BarrelJack:BarrelJack_Horizontal"))

    # Input filter capacitor C1 at (80, 70)
    instances.append(create_symbol("Device:CP", "C1", "470uF", 80, 70,
                                   "Capacitor_SMD:CP_Elec_10x10.5"))

    # +12V power symbol
    instances.append(create_power_symbol("power:+12V", 90, 50))

    # GND for input
    instances.append(create_power_symbol("power:GND", 80, 85))

    # ==================== 5V REGULATOR SECTION ====================
    # U1: LM2596S-5.0 at (130, 60)
    instances.append(create_symbol("Regulator_Switching:LM2596S-5", "U1", "LM2596S-5.0", 130, 60,
                                   "Package_TO_SOT_SMD:TO-263-5_TabPin3"))

    # Input cap C2
    instances.append(create_symbol("Device:C", "C2", "100uF", 110, 75,
                                   "Capacitor_SMD:C_1206_3216Metric"))

    # Schottky diode D1
    instances.append(create_symbol("Device:D_Schottky", "D1", "SS34", 145, 80,
                                   "Diode_SMD:D_SMA"))

    # Inductor L1
    instances.append(create_symbol("Device:L", "L1", "33uH", 160, 55,
                                   "Inductor_SMD:L_12x12mm_H8mm"))

    # Output cap C3
    instances.append(create_symbol("Device:CP", "C3", "220uF", 175, 70,
                                   "Capacitor_SMD:CP_Elec_8x10.5"))

    # LED indicator D2
    instances.append(create_symbol("Device:LED", "D2", "GREEN", 190, 75,
                                   "LED_SMD:LED_0603_1608Metric"))

    # LED resistor R1
    instances.append(create_symbol("Device:R", "R1", "1k", 190, 60,
                                   "Resistor_SMD:R_0402_1005Metric"))

    # +5V power symbol
    instances.append(create_power_symbol("power:+5V", 175, 45))

    # GND symbols for 5V section
    instances.append(create_power_symbol("power:GND", 130, 85))
    instances.append(create_power_symbol("power:GND", 175, 85))

    # ==================== 3.3V REGULATOR SECTION ====================
    # U2: LM2596S-ADJ at (130, 130)
    instances.append(create_symbol("Regulator_Switching:LM2596S-ADJ", "U2", "LM2596S-ADJ", 130, 130,
                                   "Package_TO_SOT_SMD:TO-263-5_TabPin3"))

    # Feedback resistors for 3.3V: Vout = 1.23 * (1 + R3/R4), R3=1.5k, R4=1k -> 3.08V
    instances.append(create_symbol("Device:R", "R2", "1.5k", 145, 145,
                                   "Resistor_SMD:R_0402_1005Metric"))
    instances.append(create_symbol("Device:R", "R3", "1k", 145, 160,
                                   "Resistor_SMD:R_0402_1005Metric"))

    # Input cap C4
    instances.append(create_symbol("Device:C", "C4", "100uF", 110, 145,
                                   "Capacitor_SMD:C_1206_3216Metric"))

    # Schottky diode D3
    instances.append(create_symbol("Device:D_Schottky", "D3", "SS34", 145, 150,
                                   "Diode_SMD:D_SMA"))

    # Inductor L2
    instances.append(create_symbol("Device:L", "L2", "33uH", 160, 125,
                                   "Inductor_SMD:L_12x12mm_H8mm"))

    # Output cap C5
    instances.append(create_symbol("Device:CP", "C5", "220uF", 175, 140,
                                   "Capacitor_SMD:CP_Elec_8x10.5"))

    # LED indicator D4
    instances.append(create_symbol("Device:LED", "D4", "YELLOW", 190, 145,
                                   "LED_SMD:LED_0603_1608Metric"))

    # LED resistor R4
    instances.append(create_symbol("Device:R", "R4", "470", 190, 130,
                                   "Resistor_SMD:R_0402_1005Metric"))

    # +3V3 power symbol
    instances.append(create_power_symbol("power:+3V3", 175, 115))

    # GND symbols for 3.3V section
    instances.append(create_power_symbol("power:GND", 130, 155))
    instances.append(create_power_symbol("power:GND", 145, 175))
    instances.append(create_power_symbol("power:GND", 175, 155))

    # ==================== 1.8V REGULATOR SECTION ====================
    # U3: LM2596S-ADJ at (130, 200)
    instances.append(create_symbol("Regulator_Switching:LM2596S-ADJ", "U3", "LM2596S-ADJ", 130, 200,
                                   "Package_TO_SOT_SMD:TO-263-5_TabPin3"))

    # Feedback resistors for 1.8V: Vout = 1.23 * (1 + R5/R6), R5=470, R6=1k -> 1.81V
    instances.append(create_symbol("Device:R", "R5", "470", 145, 215,
                                   "Resistor_SMD:R_0402_1005Metric"))
    instances.append(create_symbol("Device:R", "R6", "1k", 145, 230,
                                   "Resistor_SMD:R_0402_1005Metric"))

    # Input cap C6
    instances.append(create_symbol("Device:C", "C6", "100uF", 110, 215,
                                   "Capacitor_SMD:C_1206_3216Metric"))

    # Schottky diode D5
    instances.append(create_symbol("Device:D_Schottky", "D5", "SS34", 145, 220,
                                   "Diode_SMD:D_SMA"))

    # Inductor L3
    instances.append(create_symbol("Device:L", "L3", "33uH", 160, 195,
                                   "Inductor_SMD:L_12x12mm_H8mm"))

    # Output cap C7
    instances.append(create_symbol("Device:CP", "C7", "220uF", 175, 210,
                                   "Capacitor_SMD:CP_Elec_8x10.5"))

    # LED indicator D6
    instances.append(create_symbol("Device:LED", "D6", "RED", 190, 215,
                                   "LED_SMD:LED_0603_1608Metric"))

    # LED resistor R7
    instances.append(create_symbol("Device:R", "R7", "330", 190, 200,
                                   "Resistor_SMD:R_0402_1005Metric"))

    # +1V8 power symbol
    instances.append(create_power_symbol("power:+1V8", 175, 185))

    # GND symbols for 1.8V section
    instances.append(create_power_symbol("power:GND", 130, 225))
    instances.append(create_power_symbol("power:GND", 145, 245))
    instances.append(create_power_symbol("power:GND", 175, 225))

    # ==================== HIERARCHICAL LABELS ====================
    instances.append(create_hlabel("+12V", "input", 95, 50))
    instances.append(create_hlabel("+5V", "output", 200, 50))
    instances.append(create_hlabel("+3V3", "output", 200, 120))
    instances.append(create_hlabel("+1V8", "output", 200, 190))
    instances.append(create_hlabel("GND", "passive", 200, 250))

    return '\n'.join(instances)


def create_symbol(lib_id, ref, value, x, y, footprint=""):
    """Create a component symbol instance."""
    return f'''	(symbol
		(lib_id "{lib_id}")
		(at {x} {y} 0)
		(unit 1)
		(exclude_from_sim no)
		(in_bom yes)
		(on_board yes)
		(dnp no)
		(uuid "{gen_uuid()}")
		(property "Reference" "{ref}" (at {x} {y-5} 0) (effects (font (size 1.27 1.27))))
		(property "Value" "{value}" (at {x} {y+5} 0) (effects (font (size 1.27 1.27))))
		(property "Footprint" "{footprint}" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Datasheet" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Description" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(pin "1" (uuid "{gen_uuid()}"))
		(pin "2" (uuid "{gen_uuid()}"))
		(pin "3" (uuid "{gen_uuid()}"))
		(pin "4" (uuid "{gen_uuid()}"))
		(pin "5" (uuid "{gen_uuid()}"))
	)'''


def create_power_symbol(lib_id, x, y):
    """Create a power symbol instance."""
    value = lib_id.split(":")[-1]
    ref = "#PWR"
    return f'''	(symbol
		(lib_id "{lib_id}")
		(at {x} {y} 0)
		(unit 1)
		(exclude_from_sim no)
		(in_bom yes)
		(on_board yes)
		(dnp no)
		(uuid "{gen_uuid()}")
		(property "Reference" "{ref}" (at {x} {y+3} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Value" "{value}" (at {x} {y-3} 0) (effects (font (size 1.27 1.27))))
		(property "Footprint" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Datasheet" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Description" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(pin "1" (uuid "{gen_uuid()}"))
	)'''


def create_hlabel(name, shape, x, y):
    """Create a hierarchical label."""
    return f'''	(hierarchical_label "{name}"
		(shape {shape})
		(at {x} {y} 0)
		(effects (font (size 1.27 1.27)) (justify left))
		(uuid "{gen_uuid()}")
	)'''


def generate_wires():
    """Generate wire connections."""
    wires = []

    # Note: Wire connections would typically be added manually in KiCad
    # For a complete schematic, you would need to calculate exact pin positions
    # and connect them with wires. This is left as manual work in KiCad.

    # Add some descriptive text
    wires.append(f'''	(text "12V DC Input Section"
		(exclude_from_sim no)
		(at 50 40 0)
		(effects (font (size 2 2)) (justify left))
		(uuid "{gen_uuid()}")
	)''')

    wires.append(f'''	(text "5V Output (LM2596S-5.0)"
		(exclude_from_sim no)
		(at 120 40 0)
		(effects (font (size 2 2)) (justify left))
		(uuid "{gen_uuid()}")
	)''')

    wires.append(f'''	(text "3.3V Output (LM2596S-ADJ)"
		(exclude_from_sim no)
		(at 120 110 0)
		(effects (font (size 2 2)) (justify left))
		(uuid "{gen_uuid()}")
	)''')

    wires.append(f'''	(text "1.8V Output (LM2596S-ADJ)"
		(exclude_from_sim no)
		(at 120 180 0)
		(effects (font (size 2 2)) (justify left))
		(uuid "{gen_uuid()}")
	)''')

    return '\n'.join(wires)


def main():
    print("="*50)
    print("Power Supply 2 Schematic Generator")
    print("="*50)

    # Generate schematic
    sch_content = generate_schematic()

    # Write to file
    OUTPUT_FILE.write_text(sch_content, encoding='utf-8')

    print(f"[OK] Generated: {OUTPUT_FILE}")
    print("\nComponents created:")
    print("  - J1: DC Barrel Jack (12V input)")
    print("  - U1: LM2596S-5.0 (12V -> 5V)")
    print("  - U2: LM2596S-ADJ (12V -> 3.3V)")
    print("  - U3: LM2596S-ADJ (12V -> 1.8V)")
    print("  - L1-L3: 33uH inductors")
    print("  - D1-D3: SS34 Schottky diodes")
    print("  - D4-D6: LED indicators")
    print("  - C1-C7: Filter capacitors")
    print("  - R1-R7: Resistors")
    print("\n[IMPORTANT] Library references used (lib_id):")
    print("  - Device:R, Device:C, Device:CP, Device:L")
    print("  - Device:LED, Device:D_Schottky")
    print("  - Connector:Barrel_Jack_Switch")
    print("  - Regulator_Switching:LM2596S-5, LM2596S-ADJ")
    print("  - power:GND, +12V, +5V, +3V3, +1V8")
    print("\n[NOTE] lib_symbols section is empty.")
    print("       KiCad will load symbols from external libraries.")
    print("       Open in KiCad and connect wires manually.")


if __name__ == '__main__':
    main()
