"""
Schematic Templates - KiCad 회로도 템플릿 v1.3

.kicad_sch 파일 생성 기능.
v1.2: 계층 시트 지원 추가
v1.3: 타이틀 블록 동적 생성, generator_version 통합, ports 확장
"""

import uuid
from dataclasses import dataclass
from typing import Optional


def gen_uuid() -> str:
    """UUID 생성."""
    return str(uuid.uuid4())


@dataclass
class Position:
    """위치 정보."""
    x: float
    y: float
    rotation: int = 0


@dataclass
class TitleBlockInfo:
    """타이틀 블록 정보."""
    title: str
    date: str
    rev: str
    company: str
    comment1: str = ""
    comment2: str = ""


class SchematicTemplate:
    """회로도 템플릿 및 생성."""

    GRID_SIZE = 2.54  # mm, KiCad 기본 그리드
    PART_SPACING_X = 40.0  # mm, 부품 간 X 간격
    PART_SPACING_Y = 30.0  # mm, 부품 간 Y 간격
    PARTS_PER_ROW = 6  # 한 행당 부품 수

    @staticmethod
    def create_schematic(
        project_name: str,
        lib_symbols: str,
        components: str,
        wires: str = "",
        labels: str = "",
        texts: str = "",
        title_block: TitleBlockInfo = None,
        generator_version: str = "1.0.0",
    ) -> str:
        """회로도 파일 내용을 생성합니다.

        Args:
            project_name: 프로젝트 이름
            lib_symbols: lib_symbols 섹션 내용
            components: 컴포넌트 인스턴스 섹션
            wires: 와이어 섹션
            labels: 라벨 섹션
            texts: 텍스트 섹션
            title_block: 타이틀 블록 정보 (없으면 기본값 사용)
            generator_version: 생성기 버전

        Returns:
            .kicad_sch 파일 내용
        """
        schematic_uuid = gen_uuid()

        # 타이틀 블록 기본값
        if title_block is None:
            from datetime import date
            title_block = TitleBlockInfo(
                title=project_name,
                date=date.today().strftime("%Y-%m-%d"),
                rev="1.0",
                company="Auto Generated",
                comment1=f"Generated by kicad_auto_builder v{generator_version}",
            )

        # 코멘트 섹션 생성
        comments = f'(comment 1 "{title_block.comment1}")\n' if title_block.comment1 else ''
        if title_block.comment2:
            comments += f'\t\t(comment 2 "{title_block.comment2}")\n'

        return f'''(kicad_sch
	(version 20250114)
	(generator "kicad_auto_builder")
	(generator_version "{generator_version}")
	(uuid "{schematic_uuid}")
	(paper "A3")
	(title_block
		(title "{title_block.title}")
		(date "{title_block.date}")
		(rev "{title_block.rev}")
		(company "{title_block.company}")
		{comments.rstrip()}
	)
	(lib_symbols
{lib_symbols}
	)
{components}
{wires}
{labels}
{texts}
	(sheet_instances
		(path "/"
			(page "1")
		)
	)
)
'''

    @staticmethod
    def create_component_instance(
        lib_id: str,
        ref: str,
        value: str,
        x: float,
        y: float,
        rotation: int = 0,
        footprint: str = "",
        lcsc: str = "",
        project: str = "project",
    ) -> str:
        """컴포넌트 인스턴스를 생성합니다.

        Args:
            lib_id: 라이브러리 ID (LibName:SymbolName)
            ref: Reference designator
            value: 값
            x, y: 위치
            rotation: 회전 각도
            footprint: 풋프린트 이름
            lcsc: LCSC 부품번호
            project: 프로젝트 이름

        Returns:
            컴포넌트 인스턴스 문자열
        """
        component_uuid = gen_uuid()
        path_uuid = gen_uuid()

        lcsc_prop = ""
        if lcsc:
            lcsc_prop = f'''
		(property "LCSC Part" "{lcsc}" (at {x} {y + 7.62} 0) (effects (font (size 1.27 1.27)) hide))'''

        return f'''	(symbol
		(lib_id "{lib_id}")
		(at {x} {y} {rotation})
		(unit 1)
		(exclude_from_sim no)
		(in_bom yes)
		(on_board yes)
		(dnp no)
		(uuid "{component_uuid}")
		(property "Reference" "{ref}" (at {x} {y - 5.08} 0) (effects (font (size 1.27 1.27))))
		(property "Value" "{value}" (at {x} {y + 5.08} 0) (effects (font (size 1.27 1.27))))
		(property "Footprint" "{footprint}" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Datasheet" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Description" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide)){lcsc_prop}
		(instances
			(project "{project}"
				(path "/{path_uuid}" (reference "{ref}") (unit 1))
			)
		)
	)'''

    @staticmethod
    def create_power_instance(
        lib_id: str,
        value: str,
        x: float,
        y: float,
        rotation: int = 0,
        project: str = "project",
    ) -> str:
        """전원 심볼 인스턴스를 생성합니다."""
        component_uuid = gen_uuid()
        path_uuid = gen_uuid()

        return f'''	(symbol
		(lib_id "{lib_id}")
		(at {x} {y} {rotation})
		(unit 1)
		(exclude_from_sim no)
		(in_bom no)
		(on_board yes)
		(dnp no)
		(uuid "{component_uuid}")
		(property "Reference" "#PWR" (at {x} {y + 2.54} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Value" "{value}" (at {x} {y - 2.54} 0) (effects (font (size 1.27 1.27))))
		(property "Footprint" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Datasheet" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(property "Description" "" (at {x} {y} 0) (effects (font (size 1.27 1.27)) hide))
		(instances
			(project "{project}"
				(path "/{path_uuid}" (reference "#PWR") (unit 1))
			)
		)
	)'''

    @staticmethod
    def create_wire(x1: float, y1: float, x2: float, y2: float) -> str:
        """와이어를 생성합니다."""
        return f'''	(wire
		(pts (xy {x1} {y1}) (xy {x2} {y2}))
		(stroke (width 0) (type default))
		(uuid "{gen_uuid()}")
	)'''

    @staticmethod
    def create_label(name: str, x: float, y: float, rotation: int = 0) -> str:
        """네트 라벨을 생성합니다."""
        return f'''	(label "{name}"
		(at {x} {y} {rotation})
		(fields_autoplaced yes)
		(effects
			(font (size 1.27 1.27))
			(justify left bottom)
		)
		(uuid "{gen_uuid()}")
	)'''

    @staticmethod
    def create_global_label(
        name: str,
        x: float,
        y: float,
        shape: str = "passive",
        rotation: int = 0,
    ) -> str:
        """글로벌 라벨을 생성합니다.

        Args:
            name: 라벨 이름
            x, y: 위치
            shape: 'input', 'output', 'bidirectional', 'passive'
            rotation: 회전 각도
        """
        return f'''	(global_label "{name}"
		(shape {shape})
		(at {x} {y} {rotation})
		(fields_autoplaced yes)
		(effects
			(font (size 1.27 1.27))
			(justify left)
		)
		(uuid "{gen_uuid()}")
	)'''

    @staticmethod
    def create_text(text: str, x: float, y: float, rotation: int = 0) -> str:
        """텍스트 주석을 생성합니다."""
        # 줄바꿈 이스케이프
        escaped_text = text.replace("\n", "\\n")

        return f'''	(text "{escaped_text}"
		(exclude_from_sim no)
		(at {x} {y} {rotation})
		(effects
			(font (size 1.27 1.27))
			(justify left)
		)
		(uuid "{gen_uuid()}")
	)'''

    @staticmethod
    def calculate_grid_position(index: int) -> Position:
        """부품 인덱스로 그리드 위치를 계산합니다.

        Args:
            index: 부품 인덱스 (0부터 시작)

        Returns:
            Position 객체
        """
        row = index // SchematicTemplate.PARTS_PER_ROW
        col = index % SchematicTemplate.PARTS_PER_ROW

        x = 50.0 + col * SchematicTemplate.PART_SPACING_X
        y = 50.0 + row * SchematicTemplate.PART_SPACING_Y

        return Position(x=x, y=y)

    # ========== v1.4: 기능별 그룹 배치 ==========

    # 역할별 기능 그룹 매핑
    ROLE_GROUPS = {
        # 전원부 그룹
        "power": [
            "buck_5v", "buck_3v3", "buck_1v8", "buck_adj", "buck_xl1509",
            "ldo_3v3", "ldo_5v", "ldo_1v8", "ldo_ap2112",
            "reg_7805", "reg_7812", "reg_317",
        ],
        # 커넥터 그룹
        "connector": [
            "input_conn", "barrel_jack", "screw_2p", "screw_3p",
            "usb_a", "usb_c", "rj45", "hdmi",
            "conn_2p", "conn_3p", "conn_4p", "conn_6p",
        ],
        # 인터페이스 IC 그룹
        "interface": [
            "usb_hub", "usb_phy", "usb_uart", "ch340", "cp2102", "ft232",
            "rs232", "max232", "can_transceiver", "can_controller",
        ],
        # 패시브 그룹
        "passive": [
            "resistor", "capacitor", "capacitor_pol", "inductor",
            "ferrite", "fuse",
        ],
        # 반도체 그룹
        "semiconductor": [
            "led", "diode", "schottky", "zener", "tvs",
            "nmos", "pmos", "nmos_dgs", "pmos_dgs", "npn", "pnp",
        ],
        # OpAmp 그룹
        "opamp": [
            "opamp", "opamp_dual", "opamp_quad", "comparator",
            "tl072", "ne5532",
        ],
        # 기타
        "misc": [
            "crystal", "button", "testpoint",
        ],
    }

    # 그룹별 시작 위치
    GROUP_POSITIONS = {
        "connector": Position(50.0, 50.0),    # 왼쪽 상단 - 입력
        "power": Position(50.0, 120.0),       # 왼쪽 중단 - 전원부
        "interface": Position(200.0, 50.0),   # 오른쪽 상단 - IC
        "opamp": Position(200.0, 120.0),      # 오른쪽 중단 - 아날로그
        "semiconductor": Position(50.0, 190.0),  # 왼쪽 하단
        "passive": Position(200.0, 190.0),    # 오른쪽 하단 - 패시브
        "misc": Position(350.0, 50.0),        # 맨 오른쪽
    }

    @classmethod
    def get_group_for_role(cls, role: str) -> str:
        """역할에 해당하는 그룹을 반환합니다.

        Args:
            role: 부품 역할 (예: "buck_5v", "resistor")

        Returns:
            그룹 이름 또는 "misc"
        """
        role_lower = role.lower()
        for group, roles in cls.ROLE_GROUPS.items():
            if role_lower in roles:
                return group
        return "misc"

    @classmethod
    def calculate_grouped_positions(cls, parts: list) -> dict:
        """부품들을 기능 그룹별로 배치 위치를 계산합니다.

        Args:
            parts: ResolvedPart 목록 (role 속성 필요)

        Returns:
            {ref: Position, ...}
        """
        # 그룹별 부품 분류
        group_parts = {group: [] for group in cls.GROUP_POSITIONS.keys()}

        for part in parts:
            group = cls.get_group_for_role(part.role)
            group_parts[group].append(part)

        # 그룹별 위치 계산
        positions = {}
        for group, parts_in_group in group_parts.items():
            if not parts_in_group:
                continue

            base_pos = cls.GROUP_POSITIONS.get(group, Position(50.0, 50.0))
            for i, part in enumerate(parts_in_group):
                row = i // 4  # 그룹당 4열
                col = i % 4
                x = base_pos.x + col * cls.PART_SPACING_X
                y = base_pos.y + row * cls.PART_SPACING_Y
                positions[part.ref] = Position(x=x, y=y)

        return positions

    @classmethod
    def calculate_power_symbol_position(cls, component_pos: Position, pin_side: str = "bottom") -> Position:
        """부품에 인접한 전원 심볼 위치를 계산합니다.

        Args:
            component_pos: 부품 위치
            pin_side: 전원 핀 위치 ("top", "bottom", "left", "right")

        Returns:
            전원 심볼 Position
        """
        offsets = {
            "top": (0, -15.0),
            "bottom": (0, 15.0),
            "left": (-15.0, 0),
            "right": (15.0, 0),
        }
        dx, dy = offsets.get(pin_side, (0, 15.0))
        return Position(
            x=component_pos.x + dx,
            y=component_pos.y + dy
        )

    # ========== v1.2/v1.3: 계층 시트 관련 ==========

    @staticmethod
    def create_sheet_symbol(
        name: str,
        filename: str,
        x: float,
        y: float,
        width: float = 30.0,
        height: float = 20.0,
        pins: list = None,
    ) -> str:
        """루트 시트에 배치되는 서브시트 심볼을 생성합니다.

        Args:
            name: 시트 이름
            filename: 시트 파일명 (.kicad_sch)
            x, y: 위치
            width, height: 심볼 크기
            pins: 계층 핀 목록 [PortSpec, ...] 또는 [{"name": str, "type": str, "side": str}, ...]

        Returns:
            sheet 심볼 문자열
        """
        sheet_uuid = gen_uuid()

        # 계층 핀 생성 (side에 따라 좌/우 배치)
        pins_str = ""
        if pins:
            left_pins = [p for p in pins if getattr(p, 'side', p.get('side', 'left') if isinstance(p, dict) else 'left') == 'left']
            right_pins = [p for p in pins if getattr(p, 'side', p.get('side', 'left') if isinstance(p, dict) else 'left') == 'right']

            # 왼쪽 핀 (시트 왼쪽에 배치)
            pin_y = y + 2.54
            for pin in left_pins:
                if hasattr(pin, 'name'):
                    pin_name = pin.name
                    pin_type = pin.shape
                else:
                    pin_name = pin.get("name", "")
                    pin_type = pin.get("type", pin.get("shape", "passive"))
                pins_str += f'''
		(pin "{pin_name}" {pin_type}
			(at {x} {pin_y} 180)
			(effects (font (size 1.27 1.27)) (justify right))
			(uuid "{gen_uuid()}")
		)'''
                pin_y += 2.54

            # 오른쪽 핀 (시트 오른쪽에 배치)
            pin_y = y + 2.54
            for pin in right_pins:
                if hasattr(pin, 'name'):
                    pin_name = pin.name
                    pin_type = pin.shape
                else:
                    pin_name = pin.get("name", "")
                    pin_type = pin.get("type", pin.get("shape", "passive"))
                pins_str += f'''
		(pin "{pin_name}" {pin_type}
			(at {x + width} {pin_y} 0)
			(effects (font (size 1.27 1.27)) (justify left))
			(uuid "{gen_uuid()}")
		)'''
                pin_y += 2.54

        return f'''	(sheet
		(at {x} {y})
		(size {width} {height})
		(fields_autoplaced yes)
		(stroke (width 0.1524) (type solid))
		(fill (color 0 0 0 0.0000))
		(uuid "{sheet_uuid}")
		(property "Sheetname" "{name}"
			(at {x} {y - 2.54} 0)
			(effects (font (size 1.27 1.27)) (justify left bottom))
		)
		(property "Sheetfile" "{filename}"
			(at {x} {y + height + 2.54} 0)
			(effects (font (size 1.27 1.27)) (justify left top))
		){pins_str}
	)'''

    @staticmethod
    def create_hierarchical_pin(
        name: str,
        x: float,
        y: float,
        shape: str = "passive",
        rotation: int = 180,
    ) -> str:
        """서브시트 내부의 계층 핀(포트)을 생성합니다.

        이 핀은 서브시트(.kicad_sch) 내부에 배치되어
        루트 시트의 sheet 심볼 핀과 연결됩니다.

        Args:
            name: 핀 이름
            x, y: 위치
            shape: 'input', 'output', 'bidirectional', 'passive'
            rotation: 회전 각도

        Returns:
            hierarchical_label 문자열
        """
        return f'''	(hierarchical_label "{name}"
		(shape {shape})
		(at {x} {y} {rotation})
		(fields_autoplaced yes)
		(effects
			(font (size 1.27 1.27))
			(justify right)
		)
		(uuid "{gen_uuid()}")
	)'''

    @staticmethod
    def create_root_schematic(
        project_name: str,
        lib_symbols: str,
        sheet_symbols: str,
        texts: str = "",
        title_block: TitleBlockInfo = None,
        generator_version: str = "1.0.0",
    ) -> str:
        """계층 구조의 루트 회로도를 생성합니다.

        Args:
            project_name: 프로젝트 이름
            lib_symbols: lib_symbols 섹션
            sheet_symbols: 서브시트 심볼 섹션
            texts: 텍스트 주석
            title_block: 타이틀 블록 정보
            generator_version: 생성기 버전

        Returns:
            루트 .kicad_sch 파일 내용
        """
        schematic_uuid = gen_uuid()

        # 타이틀 블록 기본값
        if title_block is None:
            from datetime import date
            title_block = TitleBlockInfo(
                title=project_name,
                date=date.today().strftime("%Y-%m-%d"),
                rev="1.0",
                company="Auto Generated",
                comment1=f"Generated by kicad_auto_builder v{generator_version}",
            )

        comments = f'(comment 1 "{title_block.comment1}")\n' if title_block.comment1 else ''
        if title_block.comment2:
            comments += f'\t\t(comment 2 "{title_block.comment2}")\n'

        return f'''(kicad_sch
	(version 20250114)
	(generator "kicad_auto_builder")
	(generator_version "{generator_version}")
	(uuid "{schematic_uuid}")
	(paper "A3")
	(title_block
		(title "{title_block.title}")
		(date "{title_block.date}")
		(rev "{title_block.rev}")
		(company "{title_block.company}")
		{comments.rstrip()}
	)
	(lib_symbols
{lib_symbols}
	)
{sheet_symbols}
{texts}
	(sheet_instances
		(path "/"
			(page "1")
		)
	)
)
'''

    @staticmethod
    def create_sub_schematic(
        sheet_name: str,
        project_name: str,
        lib_symbols: str,
        components: str,
        wires: str = "",
        labels: str = "",
        hierarchical_pins: str = "",
        texts: str = "",
        sheet_uuid: str = "",
        title_block: TitleBlockInfo = None,
        generator_version: str = "1.0.0",
    ) -> str:
        """서브시트 회로도를 생성합니다.

        Args:
            sheet_name: 시트 이름
            project_name: 프로젝트 이름
            lib_symbols: lib_symbols 섹션
            components: 컴포넌트 섹션
            wires: 와이어 섹션
            labels: 로컬 라벨 섹션
            hierarchical_pins: 계층 핀 섹션
            texts: 텍스트 섹션
            sheet_uuid: 시트 UUID (루트에서 참조)
            title_block: 타이틀 블록 정보
            generator_version: 생성기 버전

        Returns:
            서브시트 .kicad_sch 파일 내용
        """
        schematic_uuid = sheet_uuid or gen_uuid()

        # 타이틀 블록 기본값
        if title_block is None:
            from datetime import date
            title_block = TitleBlockInfo(
                title=sheet_name,
                date=date.today().strftime("%Y-%m-%d"),
                rev="1.0",
                company=project_name,
                comment1=f"Sub-sheet: {sheet_name}",
            )

        comments = f'(comment 1 "{title_block.comment1}")\n' if title_block.comment1 else ''
        if title_block.comment2:
            comments += f'\t\t(comment 2 "{title_block.comment2}")\n'

        return f'''(kicad_sch
	(version 20250114)
	(generator "kicad_auto_builder")
	(generator_version "{generator_version}")
	(uuid "{schematic_uuid}")
	(paper "A4")
	(title_block
		(title "{title_block.title}")
		(date "{title_block.date}")
		(rev "{title_block.rev}")
		(company "{title_block.company}")
		{comments.rstrip()}
	)
	(lib_symbols
{lib_symbols}
	)
{components}
{wires}
{labels}
{hierarchical_pins}
{texts}
)
'''
